# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008f10d5592daf40148a2185db33b35afe8e27cf04a6d39fd8633a739706c151452804bdc9fa0277103ad95cfa7e0dec46ededd4f59c2c6613b4d35aefbf045a

test:
  secret_key_base: 5e213447c62d980cd8b020a22213e28aa02a30d35e715c12ff8062eaeddde47210bdf14a7738513ff76938163a648e99a67f9398e266ae5f3673983845cc3e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
